sudo: false
language: python


# Test test matrix is spells out each supported version of Python explicitly:
matrix:
    include:
        # has to be the same py version specified in tox.ini

        -   python: 3.7
            env: TOXENV=codestyle

        -   python: 3.0
            env: TOXENV=py30
        -   python: 3.1
            env: TOXENV=py31
        -   python: 3.2
            env: TOXENV=py32
        -   python: 3.3
            env: TOXENV=py33
        -   python: 3.4
            env: TOXENV=py34
        -   python: 3.5
            env: TOXENV=py35
        -   python: 3.6
            env: TOXENV=py36
        -   python: 3.7
            env: TOXENV=py37
        -   python: 3.8
            env: TOXENV=py38


#allow_failures:
#    # Tests with ... are allowed to fail
#    -   env: ...

install:
    - ./.travis/install.sh

script:
    - tox

branches:
    only:
        - master
        - dev

notifications:
    email:
        recipients:
            - python@michelfe.it
        on_success: always
        on_failure: always
        on_start: never   # options: [always|never|change] default: always
